### ISSUE TITLE
bug related pl/types

### ISSUE THREAD

**Issue by yumuzi234** [shanhuio/smlvm#57]
```
func main() {
	var s string
	for i := 0; i < len(s-2); i++ {}
}
```
The error message from `const.go`

```
func constCast(
	b *builder, pos *lexing.Pos, v int64, from tast.Expr, to types.T,
) tast.Expr {
	if types.IsInteger(to) && types.InRange(v, to) {
		return tast.NewCast(from, to)
	}
	b.CodeErrorf(pos, "pl.cannotCast", "cannot cast %d to %s", v, to)
	return nil
}
```

is "cannot cast 2 to []int8"
change "to", to, "to.String()", the same (I think it should be to.String()), it seems that T for string is declare in `pl/type/basic.go` does not include string or char, not sure whether that is the problem.

**Comment by h8liu** [comment]
I thought you say there are two errors. this error is actually intended. string is an alias for []int8.

FWIW, I changed the error message a little bit so that it is less confusing. Now compiling the program prints: 

`a.g:3: cannot cast const number 2 to []int8 (string)`

**Comment by h8liu** [comment]
much like string in C is actually char[] or char*
