### ISSUE TITLE
README: First sentence contains a broken link.

### ISSUE THREAD

**Issue by shurcooL** [shanhuio/smlvm#83]
The first sentence in the README contains a link:

> Small Virtual Machine (`smlvm`) provides [a simple programming language](https://github.com/shanhuio/smlvm/wiki/G-introduction) that compiles to a simulated, simple virtual machine. It is essentially a subset of Go programming language.

It points to a missing wiki page at:

https://github.com/shanhuio/smlvm/wiki/G-introduction

There are pages that exists at:

- https://github.com/shanhuio/smlvm/wiki
- https://github.com/shanhuio/smlvm/wiki/G-Language-Introduction

Perhaps you meant to link to one of those?

Also, the README contains a link named "G **languge** introduction"; the word "language" is misspelled in it.

**Comment by h8liu** [comment]
@yumuzi234 

please be more careful..
